spring.application.name=bootiful-beans
spring.datasource.connection-fetch=lazy
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost/mydatabase

spring.threads.virtual.enabled=true